# Generated by Django 4.1.7 on 2023-02-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Date quiz was published.')),
                ('quiz_attempts', models.IntegerField(default=0, verbose_name='Number of times quiz was attempted including incomplete attempts.')),
                ('quiz_completions', models.IntegerField(default=0, verbose_name='Number of times quiz was completed. Completion requires submission of e-mail address.')),
                ('average_score', models.FloatField(default=0, verbose_name='Average score across all attempts.')),
                ('average_score_completion', models.FloatField(default=0, verbose_name='Average score for quiz.')),
                ('average_time', models.FloatField(default=0, verbose_name='Average time spent on quiz across all attempts.')),
                ('average_time_to_completion', models.FloatField(default=0, verbose_name='Average time to completion.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_completions', models.IntegerField(default=0, verbose_name='number of times question was answered')),
                ('average_score', models.FloatField(default=0, verbose_name='average score for question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question')),
            ],
        ),
    ]
