# Generated by Django 4.1.7 on 2023-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='selections',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
