# Generated by Django 4.1.7 on 2023-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_votes_choice_selections_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Date quiz was published.')),
                ('quiz_attempts', models.IntegerField(default=0, verbose_name='Number of times quiz was attempted including incomplete attempts.')),
                ('quiz_completions', models.IntegerField(default=0, verbose_name='Number of times quiz was completed. Completion requires submission of e-mail address.')),
                ('average_score', models.FloatField(default=0, verbose_name='Average score across all attempts.')),
                ('average_score_completion', models.FloatField(default=0, verbose_name='Average score for quiz.')),
                ('average_time', models.FloatField(default=0, verbose_name='Average time spent on quiz across all attempts.')),
                ('average_time_to_completion', models.FloatField(default=0, verbose_name='Average time to completion.')),
            ],
        ),
    ]
