# Generated by Django 4.1.7 on 2023-02-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_simplequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequestion',
            name='answers',
            field=models.ManyToManyField(to='home.choice'),
        ),
        migrations.AddField(
            model_name='simplequestion',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SimpleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.simplequestion')),
            ],
        ),
    ]
